# Generated by Django 3.1.6 on 2021-12-05 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('estudio_socioeconomico', '0001_initial'),
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiosocioeconomico',
            name='estado',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='usuarios.estado', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='estudiosocioeconomico',
            name='estado_civil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='estudio_socioeconomico.estadocivil', verbose_name='Estado civil'),
        ),
        migrations.AddField(
            model_name='estudiosocioeconomico',
            name='localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='usuarios.localidad', verbose_name='Localidad'),
        ),
        migrations.AddField(
            model_name='estudiosocioeconomico',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='usuarios.municipio', verbose_name='Municipio'),
        ),
        migrations.AddField(
            model_name='estudiosocioeconomico',
            name='ocupacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='estudio_socioeconomico.ocupacion', verbose_name='Ocupacion'),
        ),
        migrations.AddField(
            model_name='estudiosocioeconomico',
            name='piso_es',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='estudio_socioeconomico.piso', verbose_name='El piso es'),
        ),
        migrations.AddField(
            model_name='estudiosocioeconomico',
            name='servicio_salud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='estudio_socioeconomico.serviciosalud', verbose_name='Ocupacion'),
        ),
        migrations.AddField(
            model_name='estudiosocioeconomico',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='solicitudes.solicitud', verbose_name='Solicitud'),
        ),
        migrations.AddField(
            model_name='estudiosocioeconomico',
            name='techo_es',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='estudio_socioeconomico.techo', verbose_name='El techo es'),
        ),
        migrations.AddField(
            model_name='estudiosocioeconomico',
            name='tipo_combustible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='estudio_socioeconomico.tipocombustible', verbose_name='Tipo de combustible'),
        ),
    ]
