# Generated by Django 3.1.6 on 2021-12-05 21:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudio_socioeconomico', '0002_auto_20211205_0705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiosocioeconomico',
            old_name='enfermedad_cardipatias',
            new_name='enfermedad_cardiopatias',
        ),
        migrations.RemoveField(
            model_name='estudiosocioeconomico',
            name='jefe_familia',
        ),
        migrations.RemoveField(
            model_name='estudiosocioeconomico',
            name='numero',
        ),
        migrations.AddField(
            model_name='estudiosocioeconomico',
            name='cabeza_familia',
            field=models.BooleanField(
                default=False, verbose_name='Es cabeza de familia'),
        ),
        migrations.AddField(
            model_name='estudiosocioeconomico',
            name='numero_exterior',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[
                                              django.core.validators.MinValueValidator(1)], verbose_name='Número exterior'),
        ),
        migrations.AddField(
            model_name='estudiosocioeconomico',
            name='numero_interior',
            field=models.PositiveIntegerField(default=1, validators=[
                                              django.core.validators.MinValueValidator(1)], verbose_name='Número interior'),
        ),
        migrations.AlterField(
            model_name='estudiosocioeconomico',
            name='comprobante_domicilio',
            field=models.FileField(upload_to='estudio/comprobante/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=[
                                   'png', 'jpeg', 'jpg', 'pdf'], message='Sólo se permiten imágenes PNG, JPG, JPEG o PDF.')], verbose_name='Comprobante de domicilio'),
        ),
        migrations.AlterField(
            model_name='estudiosocioeconomico',
            name='credencial',
            field=models.FileField(upload_to='estudio/ine/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=[
                                   'png', 'jpeg', 'jpg', 'pdf'], message='Sólo se permiten imágenes PNG, JPG, JPEG o PDF.')], verbose_name='Credencial INE/IFE'),
        ),
        migrations.AlterField(
            model_name='estudiosocioeconomico',
            name='enfermedad_otro',
            field=models.CharField(
                blank=True, max_length=60, null=True, verbose_name='Otro (Especifique)'),
        ),
        migrations.AlterField(
            model_name='estudiosocioeconomico',
            name='folio',
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name='Folio'),
        ),
        migrations.AlterField(
            model_name='estudiosocioeconomico',
            name='otros_caracteristicas_casa',
            field=models.CharField(
                blank=True, max_length=60, null=True, verbose_name='Otro'),
        ),
        migrations.AlterField(
            model_name='estudiosocioeconomico',
            name='receta',
            field=models.FileField(blank=True, null=True, upload_to=' estudio/receta/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=[
                                   'png', 'jpeg', 'jpg', 'pdf'], message='Sólo se permiten imágenes PNG, JPG, JPEG o PDF.')], verbose_name='Receta en caso de ser necesario'),
        ),
        migrations.AlterField(
            model_name='estudiosocioeconomico',
            name='servicio_salud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='estudio_socioeconomico.serviciosalud', verbose_name='Servicio de salud'),
        ),
    ]
