# Generated by Django 3.1.6 on 2021-12-06 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudio_socioeconomico', '0004_auto_20211205_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiosocioeconomico',
            name='edad',
            field=models.IntegerField(default=1, verbose_name='Edad'),
        ),
    ]
