# Generated by Django 3.1.6 on 2021-12-06 13:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudio_socioeconomico', '0005_estudiosocioeconomico_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiosocioeconomico',
            name='edad',
            field=models.PositiveIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='estudiosocioeconomico',
            name='numero_exterior',
            field=models.PositiveIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número exterior'),
        ),
    ]
