# Generated by Django 3.2.8 on 2021-11-17 01:34

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE,
                 parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('primer_apellido', models.CharField(
                    max_length=35, verbose_name='Primer apellido')),
                ('segundo_apellido', models.CharField(blank=True,
                 max_length=35, null=True, verbose_name='Segundo apellido')),
                ('user', models.CharField(max_length=20, verbose_name='Usuario')),
                ('contra', models.CharField(default=None,
                 max_length=20, verbose_name='Contraseña')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
