# Generated by Django 3.2.8 on 2021-12-09 00:22

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, verbose_name='Localidad')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35, verbose_name='Municipio')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.estado', verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('segundo_apellido', models.CharField(blank=True, max_length=35, null=True, verbose_name='Segundo apellido')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('calle', models.CharField(max_length=40, verbose_name='Calle')),
                ('numero_interior', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, 'El número debe estar entre 1 y 9999.'), django.core.validators.MaxValueValidator(9999, 'El número debe estar entre 1 y 9999.')], verbose_name='Número interior')),
                ('numero_exterior', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'El número debe estar entre 1 y 9999.'), django.core.validators.MaxValueValidator(9999, 'El número debe estar entre 1 y 9999.')], verbose_name='Número exterior')),
                ('colonia', models.CharField(max_length=35, verbose_name='Colonia')),
                ('codigo_postal', models.CharField(max_length=5, validators=[django.core.validators.MinLengthValidator(5, 'El código postal debe contener cinco dígitos.'), django.core.validators.RegexValidator('^[0-9]*$', 'Sólo se permiten números.')], verbose_name='Código postal')),
                ('telefono', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Sólo se permiten números.'), django.core.validators.MinLengthValidator(10, 'El teléfono debe contener diez dígitos.')], verbose_name='Teléfono')),
                ('ine', models.FileField(upload_to='usuarios/ine/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg', 'pdf'], message='Sólo se permiten imágenes PNG, JPG, JPEG o PDF.')])),
                ('dado_baja', models.BooleanField(default=False, validators=[django.core.validators.MaxLengthValidator(1, 'El campo sólo puede contener un dígito'), django.core.validators.MinValueValidator(0, 'Sólo se permiten los valores 0 y 1'), django.core.validators.MaxValueValidator(1, 'Sólo se permiten los valores 0 y 1')], verbose_name='Dado de baja')),
                ('rfc_corto', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10, 'El RFC corto debe contener diez caracteres.')], verbose_name='RFC Corto')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.estado', verbose_name='Estado')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.localidad', verbose_name='Localidad')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.municipio', verbose_name='Municipio')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='localidad',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.municipio', verbose_name='Municipio'),
        ),
    ]
