# Generated by Django 3.2.8 on 2021-12-09 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='dado_baja',
            field=models.BooleanField(default=False, verbose_name='Dado de baja'),
        ),
    ]
