# Generated by Django 3.2.8 on 2021-11-17 14:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_civil', models.CharField(max_length=20, validators=[
                 django.core.validators.MinLengthValidator(1)], verbose_name='Estado Civil')),
            ],
        ),
        migrations.CreateModel(
            name='GradoEstudios',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.CharField(max_length=20,
                 verbose_name='Último grado de estudios')),
            ],
        ),
        migrations.CreateModel(
            name='Ocupacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('ocupacion', models.CharField(
                    max_length=25, verbose_name='Ocupación')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('nombre', models.CharField(max_length=45, validators=[django.core.validators.RegexValidator(
                    '^[a-zA-Z\\s\\u00C0-\\u00FF]*$', 'Sólo se permiten letras.')], verbose_name='Nombre')),
                ('primer_apellido', models.CharField(max_length=35, validators=[django.core.validators.RegexValidator(
                    '^[a-zA-Z\\s\\u00C0-\\u00FF]*$', 'Sólo se permiten letras.')], verbose_name='Primer Apellido')),
                ('segundo_apellido', models.CharField(blank=True, max_length=35, null=True, validators=[django.core.validators.RegexValidator(
                    '^[a-zA-Z\\s\\u00C0-\\u00FF]*$', 'Sólo se permiten letras.')], verbose_name='Segundo apellido')),
                ('calle', models.CharField(max_length=34, validators=[django.core.validators.RegexValidator(
                    '^[a-zA-Z\\s\\u00C0-\\u00FF]*$', 'Sólo se permiten letras.')], verbose_name='Calle')),
                ('numero', models.PositiveIntegerField(validators=[
                 django.core.validators.MinValueValidator(1)], verbose_name='Número')),
                ('codigo_postal', models.CharField(max_length=5, validators=[
                 django.core.validators.MinLengthValidator(5)], verbose_name='Código Postal')),
                ('seccion', models.CharField(max_length=4, validators=[
                 django.core.validators.MinLengthValidator(4)], verbose_name='Sección')),
                ('telefono', models.CharField(max_length=10, validators=[
                 django.core.validators.MinLengthValidator(10)], verbose_name='Teléfono')),
                ('curp', models.CharField(max_length=18, verbose_name='CURP')),
                ('lugar_nacimiento', models.CharField(
                    max_length=40, verbose_name='Lugar de nacimiento')),
                ('fecha_nacimiento', models.DateField()),
                ('otra_ocupacion', models.CharField(blank=True,
                 max_length=40, null=True, verbose_name='Otra ocupación')),
                ('correo', models.CharField(max_length=50, verbose_name='Correo')),
                ('resumen', models.TextField(verbose_name='Resumen de la solicitud')),
                ('estado_civil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 to='solicitudes.estadocivil', verbose_name='Estado Civil')),
                ('ocupacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 to='solicitudes.ocupacion', verbose_name='Ocupación')),
                ('ultimo_grado_estudios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 to='solicitudes.gradoestudios', verbose_name='Último grado de estudios')),
            ],
        ),
    ]
