# Generated by Django 3.1.6 on 2021-12-05 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='estado',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='usuarios.estado', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='estatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='solicitudes.estatussolicitud', verbose_name='Estatus de la solicitud'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='usuarios.localidad', verbose_name='Localidad'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='usuarios.municipio', verbose_name='Municipio'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='usuarios.usuario', verbose_name='Usuario'),
        ),
    ]
