# Generated by Django 3.2.8 on 2021-11-17 15:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='correo',
            field=models.EmailField(max_length=50, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='curp',
            field=models.CharField(max_length=18, validators=[django.core.validators.RegexValidator(
                '^[A-Z]{1}[AEIOU]{1}[A-Z]{2}[0-9]{2}(0[1-9]|1[0-2])(0[1-9]|1[0-9]|2[0-9]|3[0-1])[HM]{1}(AS|BC|BS|CC|CS|CH|CL|CM|DF|DG|GT|GR|HG|JC|MC|MN|MS|NT|NL|OC|PL|QT|QR|SP|SL|SR|TC|TS|TL|VZ|YN|ZS|NE)[B-DF-HJ-NP-TV-Z]{3}[0-9A-Z]{1}[0-9]{1}$')], verbose_name='CURP'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='lugar_nacimiento',
            field=models.CharField(max_length=40, validators=[
                                   django.core.validators.RegexValidator('[^0-9]')], verbose_name='Lugar de nacimiento'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='seccion',
            field=models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(
                4), django.core.validators.RegexValidator('^[0-9]*$', 'Sólo se permiten números.')], verbose_name='Sección'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='telefono',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(
                10), django.core.validators.RegexValidator('^[0-9]*$', 'Sólo se permiten números.')], verbose_name='Teléfono'),
        ),
    ]
