# Generated by Django 3.2.8 on 2021-12-04 17:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_auto_20211117_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstatusSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='solicitud',
            options={'verbose_name': 'Solicitud', 'verbose_name_plural': 'Solicitudes'},
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='estado_civil',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='lugar_nacimiento',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='ocupacion',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='otra_ocupacion',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='ultimo_grado_estudios',
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='calle',
            field=models.CharField(max_length=34, verbose_name='Calle'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='codigo_postal',
            field=models.CharField(max_length=5, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.RegexValidator('^[0-9]*$', 'Sólo se permiten números.')], verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='correo',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='resumen',
            field=models.TextField(blank=True, null=True, verbose_name='Resumen de la solicitud'),
        ),
        migrations.DeleteModel(
            name='EstadoCivil',
        ),
        migrations.DeleteModel(
            name='GradoEstudios',
        ),
        migrations.DeleteModel(
            name='Ocupacion',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='estatus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='solicitudes.estatussolicitud', verbose_name='Estatus de la solicitud'),
        ),
    ]
